version: '3.7'

services:
  redis:
    image: redis:5-alpine
    command: redis-server --requirepass devpassword
    volumes:
      - vos_redis:/var/lib/redis/data
    ports:
      - '6379:6379'


  celery:
    image: cuts:devel
    command: celery worker -l debug -A cuts.blueprints.img.tasks
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - redis


  cuts:
    image: cuts:devel
    # command: >
    #   gunicorn -c "/cuts/config/gunicorn.py" "cuts.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/cuts'
      - './images:/vos/images:ro'
    ports:
      - '8000:8000'
    depends_on:
      - celery


networks:
  default:
    name: cuts_net
    attachable: true

volumes:
  vos_redis:
