version: '3.9'

services:
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass devpassword
    restart: "no"
    volumes:
      - redis:/data
    networks:
      - vos_net
    ports:
      - '6379:6379'


  celery:
    image: astrolabe/cuts
    command: celery -A cuts.blueprints.img.tasks worker -l debug
    restart: "no"
    networks:
      - vos_net
    depends_on:
      - redis


  cuts:
    image: astrolabe/cuts
    restart: "no"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - ./images:/usr/local/data/vos/images:ro
    ports:
      - '8000:8000'
    networks:
      - vos_net
    depends_on:
      - celery


networks:
  vos_net:
    name: vos_net
    external: true

volumes:
  redis:
  pgdata:
