version: '3'

services:
  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass devpassword
    networks:
      - net
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  web:
    # image: astrolabe/cuts
    image: cuts:latest
    command: >
      gunicorn -c "python:config.gunicorn"
        "cuts.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    networks:
      - net
    volumes:
      - './images:/vos/images:ro'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A cuts.blueprints.img.tasks
    env_file:
      - '.env'
    networks:
      - net


networks:
  net:

volumes:
  redis:
