version: '3.7'

services:
  redis:
    image: redis:5.0.14-alpine
    command: redis-server --requirepass devpassword
    deploy:
      restart_policy:
        condition: none
    volumes:
      - redis:/data
    networks:
      - vos_net
    ports:
      - '6379:6379'


  celery:
    image: astrolabe/cuts
    command: celery -A cuts.blueprints.img.tasks worker -l debug
    deploy:
      restart_policy:
        condition: none
    networks:
      - vos_net
    depends_on:
      - redis


  cuts:
    image: astrolabe/cuts
    deploy:
      restart_policy:
        condition: none
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - ./images:/usr/local/data/vos/images:ro
    ports:
      - '8000:8000'
    networks:
      - vos_net
    depends_on:
      - celery


networks:
  vos_net:
    name: vos_net
    external: true

volumes:
  redis:
  pgdata:
