version: '3.7'

services:
  cuts:
    build: .
    image: cuts:devel
    command: >
      gunicorn -c "python:config.gunicorn"
        --reload
        "cuts.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    networks:
      - net
    volumes:
      - '.:/cuts'
      - './images:/vos/images:ro'
    ports:
      - '8000:8000'

  celery:
    build: .
    image: cuts:devel
    command: celery worker -l debug -A cuts.blueprints.img.tasks
    networks:
      - net
    volumes:
      - '.:/cuts'


networks:
  net:
    external:
      name: vos_net
