version: '3.7'

services:
  redis:
    image: redis:5.0-alpine
    command: redis-server --requirepass devpassword
    deploy:
      restart_policy:
        condition: none
    volumes:
      - redis:/data
    ports:
      - '6379:6379'


  celery:
    image: cuts:devel
    command: celery worker -l debug -A cuts.blueprints.img.tasks
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - redis


  cuts:
    image: cuts:devel
    deploy:
      restart_policy:
        condition: none
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - './images:/vos/images:ro'
    ports:
      - '8000:8000'
    depends_on:
      - celery


networks:
  default:
    name: vos_net
    attachable: true

volumes:
  redis:
