---
openapi: 3.0.2
info:
  title: Astrolabe Image & Cutout Server (CUTS) API documentation
  description: API for the Astrolabe Image & Cutout Server (CUTS)
  contact:
    email: hickst@arizona.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
- url: https://hector.cyverse.org/cuts
tags:
- name: users
  description: Operations available to regular users
- name: admins
  description: Secured Admin-only calls
paths:
  /img/fetch:
    get:
      tags:
      - users
      summary: Fetch a specific image by record id
      description: |
        Fetch the entire image whose metadata record has the given id.
      operationId: fetch_image
      parameters:
      - name: id
        in: query
        description: Record number (id) for record to be fetched.
        required: true
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          format: int
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItem'
        "400":
          description: bad input parameter
components:
  schemas:
    InventoryItem:
      required:
      - id
      - manufacturer
      - name
      - releaseDate
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
    Manufacturer:
      required:
      - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: https://www.acme-corp.com
        phone:
          type: string
          example: 408-867-5309
